### ISSUE TITLE
Feature Update

### ISSUE THREAD

**Issue by Github-contribute** [tomfong/simple-qr#51]
1. Adopt Material You 
2. Pls add option to Scanned URL open through other apps. (2. Main priority for me to open this issue)
3. Add quick title for QR Scanner
@tomfong

**Comment by Github-contribute** [comment]
I mean quick notification toggle. It helps to quick scan. @tomfong

**Comment by tomfong** [comment]
Hi @Github-contribute 

Your suggested feature #2 was implemented in v2.8.0. Please update your app.

Meanwhile feature #3 is under development. Please stay tuned for future update.

Thank you for your support.
