### ISSUE TITLE
Add search engines

### ISSUE THREAD

**Issue by Senor-S** [tomfong/simple-qr#57]
Hi,
could you add Ecosia as a search engine?
https://www.ecosia.org/
And maybe Open Food Facts for barcodes:
https://world.openfoodfacts.org/

Great app, thanks for your work!

**Comment by tomfong** [comment]
Let me study it.

Thx for your support.

**Comment by tomfong** [comment]
Hi @Senor-S

I've added Ecosia in version 3.1.0. Please update your app on the store.

For Open Food Facts, it's still under studying.

Thx for your support.

**Comment by tomfong** [comment]
Hi @Senor-S

I've added Open Food Facts in version 3.2.0. Please update your app on the store once it is available.

The app will show a button "Facts" if it detects an EAN barcode.

Thx for your support.
