### ISSUE TITLE
Exit App Window

### ISSUE THREAD

**Issue by KobeLAL** [tomfong/simple-qr#62]
Is it possible to permanently switch off the window when exiting? I have already rated the app.

**Comment by tomfong** [comment]
which OS are you using?

**Comment by KobeLAL** [comment]
Android 13 QPR1 Beta, Pixel 6.

**Comment by tomfong** [comment]
The app should be closed and stopped after you exit the app from back button or Setting > Exit App.

**Comment by tomfong** [comment]
Or do you mean you want an option to hide the Exit App window permanently?

**Comment by KobeLAL** [comment]
Yes, the window when I close the app via the back button. So exit or rate the app.

**Comment by tomfong** [comment]
Noted. It is a good idea to have this option.

**Comment by tomfong** [comment]
The feature has been implemented in v3.3.0. Please wait for the update.
