### ISSUE TITLE
Add location option to QR code generator

### ISSUE THREAD

**Issue by MedwardR** [tomfong/simple-qr#74]
Wonderful app by the way!

**Data type:**
https://developer.android.com/reference/android/location/Location.html

**Here's an example of an app with this feature:**
https://github.com/SecUSo/privacy-friendly-qr-scanner
![Screenshot_20240128-1545262024-01-28_15-51-21_2388.png](https://github.com/tomfong/simple-qr/assets/117788102/17204e53-7d59-4e60-b847-17c37ef070ad)

Thank you!

**Comment by tomfong** [comment]
This has been implemented in the new version 4.1.0.
Please update the app when it is available.
Please create another issue if the update does not meet your expectation.
